[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    -v
    --tb=short
    --strict-markers
    --disable-warnings
    --cov=core
    --cov=crud
    --cov=models
    --cov=routers
    --cov=schemas
    --cov=services
    --cov-report=html
    --cov-report=term-missing
    --cov-config=.coveragerc
markers =
    unit: модульные тесты
    integration: интеграционные тесты
    e2e: сквозные тесты